<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>Red_Panda_Bazaar_Code</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableHarmony>true</EnableHarmony>
        <OutputPath>out\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.2"/>
    </ItemGroup>

    <Target Name="UpdateModVersion" BeforeTargets="BeforeBuild">
        <Exec Command="python &quot;$(ProjectDir)scripts\UpdateVersion.py&quot;"/>
    </Target>

</Project>
